![LogoECG](logoTCE_ECG_withR.jpg)

### CURSO: INTRODUÇÃO AO SOFTWARE R

Marcos F Silva - 15/03/2016


<center> 

**RESOLUÇÃO DA LISTA DE EXERCÍCIOS 01**  
Tópico: Introdução

</center>

***

>**1** Crie um vetor chamado `vec` contendo os elementos {26, NA, 72, 45, 12, 16, NA, 88} e obtenha o que se pede:

>**a)** Obtenha um novo vetor (`vec1`) contendo o primeiro e o último elementos do vetor `vec`;

In [6]:
vec <- c(26, NA, 72, 45, 12, 16, NA, 88)
vec1 <- vec[c(1, length(vec))]
vec1

[1] 26 88

>**b)** Insira entre os elementos 72 e 45 do vetor `vec` os elementos {24, 13, 42}.   
**Dica**: a função `append()` pode ser útil;

In [5]:
append(vec, c(24, 13, 42), 3)

 [1] 26 NA 72 24 13 42 24 13 42 24 13 42 45 12 16 NA 88

>**c)** Obtenha o produto dos elementos do vetor `vec`;

In [11]:
prod(vec, na.rm=TRUE)

[1] 1423319040

>**d)** Obtenha os valores que não sejam NAs;

In [12]:
vec[!is.na(vec)]

[1] 26 72 45 12 16 88

>**e)** Obtenha os valores maiores que a média dos elementos do vetor `vec`.

In [20]:
vec[vec > mean(vec, na.rm=TRUE)]

[1] NA 72 45 NA 88

>**f)** Obtenha um vetor contendo os valores que imediatamente antecedem e sucedem a cada NA.   
**Dica**: a função `which()` pode ser útil;    


In [41]:
vec[c(which(is.na(vec)) - 1, which(is.na(vec)) + 1)]

[1] 26 16 72 88

>**g)** Dados os vetores `a <- c(14, 27, 45, 72, 19, -12)` e `b <- c(6, 9, 8, NA, 7, 5)`, calcule $a + b$;

In [42]:
a <- c(14, 27, 45, 72, 19, -12)
b <- c(6, 9, 8, NA, 7, 5)
a + b

[1] 20 36 53 NA 26 -7

>**h)** Crie um vetor `num_pares` contendo os números inteiros pares menores que 100;

In [44]:
num_pares <- seq(2, 98, 2)
num_pares

 [1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
[26] 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98

>**i)** Exclua deste vetor os valores maiores que 60 e menores que 80;

In [45]:
vv <- num_pares[!(num_pares > 60 & num_pares < 80)]
vv

 [1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
[26] 52 54 56 58 60 80 82 84 86 88 90 92 94 96 98

>**j)** Encontre a variância dos valores remanescentes.

In [46]:
var(vv)

[1] 885.897435897436

***

> **2** O volume de um cone de raio R e altura H é dado por $\frac{1}{3} \times \pi \times R^2 \times H$. Tendo obtido o volume e a altua de alguns cones dados a seguir, calcule o volume de cada um deles.

$$R = \{2.27, 1.98, 1.69, 1.88, 1.64, 2.14\}$$
$$H = \{8.28, 8.04, 9.06, 8.70, 7.58, 8.34\}$$

In [22]:
cones <- data.frame(R = c(2.27, 1.98, 1.69, 1.88, 1.64, 2.14),
                    H = c(8.28, 8.04, 9.06, 8.70, 7.58, 8.34))

cones$volume <- round(1/3 * pi * cones$R ^ 2 * cones$H, 2)
cones

     R    H volume
1 2.27 8.28  44.68
2 1.98 8.04  33.01
3 1.69 9.06  27.10
4 1.88 8.70  32.20
5 1.64 7.58  21.35
6 2.14 8.34  40.00

***

>**3** Calcule o que se pede:

**a)** $3 + 9 / 5$

In [48]:
3 + 9 / 5

[1] 4.8

**b)** $56^4 + \frac{29}{5}$

In [49]:
56 ^ 4 + 29 / 5

[1] 9834501.8

**c)** $\sqrt{76}$

In [50]:
sqrt(76)

[1] 8.71779788708135

**d)** $\ln{12345}$

In [52]:
log(12345)

[1] 9.42100640177928

**e)** $\log_2{12345}$

In [53]:
log2(12345)

[1] 13.5916392160301

**f)** $\log_{10}{12345}$

In [54]:
log10(12345)

[1] 4.09149109426795

**g)** $\binom{6}{2}$    
combinatório de seis, dois a dois (**Dica**: existe uma função que calcula isso).

In [55]:
choose(6, 2)

[1] 15

**h)** $| 18 - 50 |$

In [56]:
abs(18 - 50)

[1] 32

**i)** $\sin(\pi), \cos(\pi), \tan(\pi)$

In [59]:
sin(pi); cos(pi); tan(pi)

[1] 1.22460635382238e-16

[1] -1

[1] -1.22460635382238e-16

**j)** Arredonde o valor de $\pi$ para 4 casas decimais;

In [47]:
round(pi, 4)

[1] 3.1416

***

>**4** Dada a matriz **A** definida a seguir, obtenha o que se pede: 

</br>

<center>
$ A = 
\begin{bmatrix}
35 & 72 & 45 \\
20 &  9 & 17 \\ 
13 & 16 & 78
\end{bmatrix}
$
</center> 


In [60]:
A <- matrix(c(35, 20, 13, 73, 9, 16, 45, 17, 78), nrow=3)
A


     [,1] [,2] [,3]
[1,]   35   73   45
[2,]   20    9   17
[3,]   13   16   78

>**a)** obtenha os elementos da diagonal principal. **Dica**: existe uma função que faz isso...; 

In [62]:
diag(A)

[1] 35  9 78

>**b)** obtenha a soma dos elementos da matriz; 

In [63]:
sum(A)

[1] 306

>**c)** obtenha a soma dos elementos da primeira linha e da segunda coluna $(A_{11}+A_{12}+A_{13}+A_{12}+A_{22}+A_{32})$

In [65]:
sum(A[1,], A[,2])

[1] 251

>**d)** obtenha a soma da primeira coluna com com a terceira linha $(A_{.1}+A_{3.})$

In [66]:
A[,1] + A[3,]

[1] 48 36 91

>**e)** faça a trasposição da matriz;

In [67]:
t(A)

     [,1] [,2] [,3]
[1,]   35   20   13
[2,]   73    9   16
[3,]   45   17   78

>**f)** crie duas novas colunas com os valores: coluna 4:{27, 48, 23}, coluna 5:{12, 3, 9};

In [68]:
A <- cbind(A, c(27, 48, 23), c(12, 3, 9))
A

     [,1] [,2] [,3] [,4] [,5]
[1,]   35   73   45   27   12
[2,]   20    9   17   48    3
[3,]   13   16   78   23    9

>**g)** substitua a terceira coluna de $A$ pela soma da segunda e terceira colunas;   

In [69]:
A[,3] <- A[, 2] + A[, 3]
A

     [,1] [,2] [,3] [,4] [,5]
[1,]   35   73  118   27   12
[2,]   20    9   26   48    3
[3,]   13   16   94   23    9

***

>**5** Considerere o data frame definido a seguir:
```
df <- data.frame(nome = c('Marcos', 'João', 'José', NA, 'Maria', 'Helena', 'Jordana'),
                 idade= c(44, 26, NA, 29, 41, 55, 72))  
```                 


>**a)** Obtenha as linhas para as quais existam NA.   
>**Dica**: a função `complete.cases()` pode ser útil;

In [16]:
df <- data.frame(nome = c('Marcos', 'João', 'José', NA, 'Maria', 'Helena', 'Jordana'),
                 idade= c(44, 26, NA, 29, 41, 55, 72),
                stringsAsFactors=FALSE)

df

     nome idade
1  Marcos    44
2   João    26
3   José    NA
4    <NA>    29
5   Maria    41
6  Helena    55
7 Jordana    72

In [17]:
df[!complete.cases(df),]

   nome idade
3 José    NA
4  <NA>    29

>**b)** Obtenha a soma dos valores da coluna `idade`;

In [18]:
sum(df$idade, na.rm=TRUE)

[1] 267

>**c)** Selecione a linha contendo o nome da pessoa de menor idade;

In [19]:
df[which.min(df$idade),]

   nome idade
2 João    26

>**d)** Obtenha as linas para as quais não existam NA;

In [20]:
df[complete.cases(df),]

     nome idade
1  Marcos    44
2   João    26
5   Maria    41
6  Helena    55
7 Jordana    72

>**e)** Calcule as dimensões de `df['idade']` e `df[['idade']]`. Use a função `dim()`;

In [21]:
dim(df['idade']); dim(df[['idade']])

[1] 7 1

NULL

>**f)** Obtenha os nomes das variáveis do data frame `df`;

In [10]:
names(df)

[1] "nome"  "idade"

>**g)** Adicione ao data frame os seguintes valores {Felipe, 36}, {Carla, 49} e {Rosane, 18};

In [22]:
df <- rbind(df,
            c("Felipe", 36),
            c("Carla", 49),
            c("Rosana", 18))

df

      nome idade
1   Marcos    44
2    João    26
3    José  <NA>
4     <NA>    29
5    Maria    41
6   Helena    55
7  Jordana    72
8   Felipe    36
9    Carla    49
10  Rosana    18

>**h)** Obtenha os números das linhas para as quais existam NA;

In [24]:
which(!complete.cases(df))

[1] 3 4

***

>**6** Experimente o comando `which.min(c(3,5,1,7,8))`. Explique o valor retornado pela função.

In [23]:
which.min(c(3,5,1,7,8))

[1] 3

A função retorna a posição do menor valor existente no vetor.

>**7** Considere a lista **`x.lis`** definida da seguinte forma: `x.lis <- list(a=1:10, b=letters[1:3], c=matrix(1:10,ncol=2))`.

>**a)** Obtenha a soma acumulada dos elementos da primeira componente;

In [26]:
x.lis <- list(a=1:10, b=letters[1:3], c=matrix(1:10,ncol=2))
cumsum(x.lis$a)        # opção 1 - usando o operador $
cumsum(x.lis[['a']])   # opção 2 - usando duplo colchetes


 [1]  1  3  6 10 15 21 28 36 45 55

 [1]  1  3  6 10 15 21 28 36 45 55

>**b)** Obtenha a segunda componente;

In [27]:
x.lis[2]   # opção 1 - usando indexação por posição
x.lis['b'] # opção 2 - usando indexação por nome

$b
[1] "a" "b" "c"


$b
[1] "a" "b" "c"


>**c)** Obtenha os nomes das componentes da lista;

In [28]:
names(x.lis)

[1] "a" "b" "c"

>**d)** Adicione o vetor **`vec`** criado anteriormente à lista; 

In [30]:
x.lis$d <- vec
x.lis

$a
 [1]  1  2  3  4  5  6  7  8  9 10

$b
[1] "a" "b" "c"

$c
     [,1] [,2]
[1,]    1    6
[2,]    2    7
[3,]    3    8
[4,]    4    9
[5,]    5   10

$d
[1] 26 NA 72 45 12 16 NA 88


>**8** Considere que você possua dados sobre o peso (em kg) e altura (em cm) de um conjunto de pessoas, conforme mostrado na tabela abaixo.

</br>

Nome   | Altura | Peso   
-------|--------|-----  
Pedro  | 180    | 87   
José   | 165    | 58   
Maria  | 160    | 65   
Sandra | 193    | 100 


Calcule o índice de massa corporal das 4 pessoas e identifique qual delas está com o IMC maior que 25.

Obs. O Indíce de Massa Corporal (IMC) é dado por:

$$IMC = \frac{peso(kg)}{[altura(m)]^2}$$



In [32]:
## Criação do data frame
dados <- data.frame(Nome = c('Pedro', 'José', 'Maria', 'Sandra'),
                  Altura = c(180, 165, 160, 193),
                  Peso = c(87, 58, 65, 100),
                  stringsAsFactors=FALSE)

dados

    Nome Altura Peso
1  Pedro    180   87
2  José    165   58
3  Maria    160   65
4 Sandra    193  100

In [35]:
## Cálculo do IMC
dados$imc <- round(dados$Peso / (dados$Altura / 100) ^ 2, 2)
dados

    Nome Altura Peso   imc
1  Pedro    180   87 26.85
2  José    165   58 21.30
3  Maria    160   65 25.39
4 Sandra    193  100 26.85

In [36]:
## Pessoa com IMC maior que 25
dados[dados$imc > 25,]

    Nome Altura Peso   imc
1  Pedro    180   87 26.85
3  Maria    160   65 25.39
4 Sandra    193  100 26.85